import type { WorkspaceProbe } from './types'

const shared = {
  architecture: 'amd64',
  cpuCores: 4,
  dataQuality: 'valid',
  memoryTotal: '8 GB',
  diskTotal: '80 GB',
} as const

/** Visual and component-test fixture. Production data is supplied by the workspace adapter. */
export const demoProbes: ReadonlyArray<WorkspaceProbe> = [
  {
    ...shared,
    id: 'tokyo-web-01',
    name: '东京 Web 01',
    group: '亚洲',
    region: '东京',
    operatingSystem: 'Debian 12',
    connection: 'online',
    freshness: 'fresh',
    ageLabel: '8 秒前',
    cpu: 12,
    memory: 54,
    disk: 31,
    ping: 28,
    uploadRate: '1.2',
    downloadRate: '8.4 MB/s',
    uploadTotal: '86.4 GB',
    downloadTotal: '428.7 GB',
    uptime: '12天 4小时',
  },
  {
    ...shared,
    id: 'hong-kong-db-01',
    name: '香港 DB 01',
    group: '亚洲',
    region: '香港',
    operatingSystem: 'Ubuntu 24.04',
    cpuCores: 8,
    memoryTotal: '16 GB',
    diskTotal: '160 GB',
    connection: 'online',
    freshness: 'fresh',
    ageLabel: '12 秒前',
    cpu: 7,
    memory: 68,
    disk: 43,
    ping: 35,
    uploadRate: '2.4',
    downloadRate: '12.8 MB/s',
    uploadTotal: '152.1 GB',
    downloadTotal: '711.5 GB',
    uptime: '24天 7小时',
  },
  {
    ...shared,
    id: 'frankfurt-02',
    name: '法兰克福 02',
    group: '欧洲',
    region: '德国',
    operatingSystem: 'Debian 12',
    connection: 'online',
    freshness: 'delayed',
    ageLabel: '2 分钟前',
    cpu: 24,
    memory: 41,
    disk: 56,
    ping: 186,
    uploadRate: '0.8',
    downloadRate: '4.1 MB/s',
    uploadTotal: '61.7 GB',
    downloadTotal: '288.3 GB',
    uptime: '8天 19小时',
  },
  {
    ...shared,
    id: 'new-york-api-01',
    name: '纽约 API 01',
    group: '北美',
    region: '美国',
    operatingSystem: 'AlmaLinux 9',
    connection: 'online',
    freshness: 'stale',
    ageLabel: '8 分钟前',
    cpu: 16,
    memory: 37,
    disk: 29,
    ping: 142,
    uploadRate: '1.8',
    downloadRate: '6.2 MB/s',
    uploadTotal: '95.2 GB',
    downloadTotal: '340.8 GB',
    uptime: '17天 2小时',
  },
  {
    ...shared,
    id: 'singapore-edge',
    name: '新加坡 Edge',
    group: '亚洲',
    region: '新加坡',
    operatingSystem: 'Debian 12',
    connection: 'offline',
    freshness: 'stale',
    ageLabel: '18 分钟前',
    cpu: null,
    memory: null,
    disk: null,
    ping: null,
    uploadRate: null,
    downloadRate: null,
    uploadTotal: '42.8 GB',
    downloadTotal: '201.3 GB',
    uptime: null,
  },
  {
    ...shared,
    id: 'osaka-backup',
    name: '大阪 Backup',
    group: '亚洲',
    region: '大阪',
    operatingSystem: 'Debian 12',
    connection: 'unknown',
    freshness: 'missing',
    ageLabel: '暂无上报',
    cpu: null,
    memory: null,
    disk: null,
    ping: null,
    uploadRate: null,
    downloadRate: null,
    uploadTotal: null,
    downloadTotal: null,
    uptime: null,
  },
  {
    ...shared,
    id: 'seoul-cache',
    name: '首尔 Cache',
    group: '亚洲',
    region: '首尔',
    operatingSystem: 'Ubuntu 24.04',
    connection: 'online',
    freshness: 'fresh',
    ageLabel: '10 秒前',
    cpu: 9,
    memory: 47,
    disk: 38,
    ping: 46,
    uploadRate: '1.1',
    downloadRate: '7.9 MB/s',
    uploadTotal: '73.6 GB',
    downloadTotal: '304.2 GB',
    uptime: '31天 8小时',
  },
  {
    ...shared,
    id: 'london-worker',
    name: '伦敦 Worker',
    group: '欧洲',
    region: '英国',
    operatingSystem: 'Debian 12',
    connection: 'online',
    freshness: 'fresh',
    ageLabel: '14 秒前',
    cpu: 31,
    memory: 62,
    disk: 49,
    ping: 171,
    uploadRate: '0.9',
    downloadRate: '5.3 MB/s',
    uploadTotal: '81.9 GB',
    downloadTotal: '390.5 GB',
    uptime: '9天 14小时',
  },
  {
    ...shared,
    id: 'paris-gateway',
    name: '巴黎 Gateway',
    group: '欧洲',
    region: '法国',
    operatingSystem: 'Ubuntu 24.04',
    connection: 'online',
    freshness: 'fresh',
    ageLabel: '9 秒前',
    cpu: 18,
    memory: 58,
    disk: 44,
    ping: 164,
    uploadRate: '1.4',
    downloadRate: '5.9 MB/s',
    uploadTotal: '68.2 GB',
    downloadTotal: '317.6 GB',
    uptime: '15天 6小时',
  },
  {
    ...shared,
    id: 'amsterdam-relay',
    name: '阿姆斯特丹 Relay',
    group: '欧洲',
    region: '荷兰',
    operatingSystem: 'Debian 12',
    connection: 'online',
    freshness: 'fresh',
    ageLabel: '11 秒前',
    cpu: 14,
    memory: 45,
    disk: 36,
    ping: 158,
    uploadRate: '1.7',
    downloadRate: '6.6 MB/s',
    uploadTotal: '77.4 GB',
    downloadTotal: '352.9 GB',
    uptime: '22天 11小时',
  },
  {
    ...shared,
    id: 'toronto-relay',
    name: '多伦多 Relay',
    group: '北美',
    region: '加拿大',
    operatingSystem: 'Ubuntu 24.04',
    connection: 'online',
    freshness: 'fresh',
    ageLabel: '13 秒前',
    cpu: 22,
    memory: 51,
    disk: 40,
    ping: 151,
    uploadRate: '1.5',
    downloadRate: '6.8 MB/s',
    uploadTotal: '104.5 GB',
    downloadTotal: '432.6 GB',
    uptime: '18天 3小时',
  },
  {
    ...shared,
    id: 'los-angeles-storage',
    name: '洛杉矶 Storage',
    group: '北美',
    region: '美国',
    operatingSystem: 'Debian 12',
    memoryTotal: '32 GB',
    diskTotal: '1 TB',
    connection: 'online',
    freshness: 'fresh',
    ageLabel: '7 秒前',
    cpu: 11,
    memory: 39,
    disk: 64,
    ping: 137,
    uploadRate: '2.1',
    downloadRate: '9.7 MB/s',
    uploadTotal: '226.8 GB',
    downloadTotal: '1.2 TB',
    uptime: '46天 9小时',
  },
]
